sudo: false
language: python
python:
  - 3.6
before_script:
- pip install tox
- source ~/virtualenv/python3.5/bin/activate
# test script
script: tox
notifications:
  on_success: change
  on_failure: always
