sudo: false
language: python
python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - 3.6
before_script:
- pip install .
script:
- python setup.py test
- if [[ $TRAVIS_PYTHON_VERSION == '3.6' ]]; then pip install -U flake8 flake8-mypy; flake8 .; fi
notifications:
  on_success: change
  on_failure: always
